_target_: src.conf.DataConfig
dataset_path: ${hydra.runtime.cwd}/../data/original_processed/resized
cached_dataset_path: ${hydra.runtime.cwd}/../data/original_processed/resized
batch_size: 4
split_method: LOC_STRATIFIED_SPLIT
compound_mapping:
  1: Berberine Chloride
  2: Brefeldin A
  3: Fluphenazine
  4: Latrunculin B
  5: Nocodazole
  6: Rapamycin
  7: Rotenone
  8: Tetrandrine
  9: Berberine Chloride
  10: Brefeldin A
  11: Fluphenazine
  12: Latrunculin B
  13: Nocodazole
  14: Rapamycin
  15: Rotenone
  16: Tetrandrine
concentration_mapping:
  1 : 50
  2 : 25
  3 : 12.5
  4 : 6.25
  5 : 3.166666667
  6 : 1.583333333
  7 : 0.75
  8 : 0.416666667
  9 : 0.166666667
  10 : 0.083333333
  11 : 0.041666667
  12 : 50
  13 : 25
  14 : 12.5
  15 : 6.25
  16 : 3.166666667
  17 : 1.583333333
  18 : 0.75
  19 : 0.416666667
  20 : 0.166666667
  21 : 0.083333333
  22 : 0.041666667
  23 : 0
  24 : 0
label2id:
  Berberine Chloride_0.04 : 0
  Berberine Chloride_0.08 : 1
  Berberine Chloride_0.17 : 2
  Berberine Chloride_0.42 : 3
  Berberine Chloride_0.75 : 4
  Berberine Chloride_1.58 : 5
  Berberine Chloride_12.5 : 6
  Berberine Chloride_25.0 : 7
  Berberine Chloride_3.17 : 8
  Berberine Chloride_50.0 : 9
  Berberine Chloride_6.25 : 10
  Brefeldin A_0.04 : 11
  Brefeldin A_0.08 : 12
  Brefeldin A_0.17 : 13
  Brefeldin A_0.42 : 14
  Brefeldin A_0.75 : 15
  Brefeldin A_1.58 : 16
  Brefeldin A_12.5 : 17
  Brefeldin A_25.0 : 18
  Brefeldin A_3.17 : 19
  Brefeldin A_50.0 : 20
  Brefeldin A_6.25 : 21
  DFSO_0.0 : 22
  Fluphenazine_0.04 : 23
  Fluphenazine_0.08 : 24
  Fluphenazine_0.17 : 25
  Fluphenazine_0.42 : 26
  Fluphenazine_0.75 : 27
  Fluphenazine_1.58 : 28
  Fluphenazine_12.5 : 29
  Fluphenazine_25.0 : 30
  Fluphenazine_3.17 : 31
  Fluphenazine_50.0 : 32
  Fluphenazine_6.25 : 33
  Latrunculin B_0.04 : 34
  Latrunculin B_0.08 : 35
  Latrunculin B_0.17 : 36
  Latrunculin B_0.42 : 37
  Latrunculin B_0.75 : 38
  Latrunculin B_1.58 : 39
  Latrunculin B_12.5 : 40
  Latrunculin B_25.0 : 41
  Latrunculin B_3.17 : 42
  Latrunculin B_50.0 : 43
  Latrunculin B_6.25 : 44
  Nocodazole_0.04 : 45
  Nocodazole_0.08 : 46
  Nocodazole_0.17 : 47
  Nocodazole_0.42 : 48
  Nocodazole_0.75 : 49
  Nocodazole_1.58 : 50
  Nocodazole_12.5 : 51
  Nocodazole_25.0 : 52
  Nocodazole_3.17 : 53
  Nocodazole_50.0 : 54
  Nocodazole_6.25 : 55
  Rapamycin_0.04 : 56
  Rapamycin_0.08 : 57
  Rapamycin_0.17 : 58
  Rapamycin_0.42 : 59
  Rapamycin_0.75 : 60
  Rapamycin_1.58 : 61
  Rapamycin_12.5 : 62
  Rapamycin_25.0 : 63
  Rapamycin_3.17 : 64
  Rapamycin_50.0 : 65
  Rapamycin_6.25 : 66
  Rotenone_0.04 : 67
  Rotenone_0.08 : 68
  Rotenone_0.17 : 69
  Rotenone_0.42 : 70
  Rotenone_0.75 : 71
  Rotenone_1.58 : 72
  Rotenone_12.5 : 73
  Rotenone_25.0 : 74
  Rotenone_3.17 : 75
  Rotenone_50.0 : 76
  Rotenone_6.25 : 77
  Tetrandrine_0.04 : 78
  Tetrandrine_0.08 : 79
  Tetrandrine_0.17 : 80
  Tetrandrine_0.42 : 81
  Tetrandrine_0.75 : 82
  Tetrandrine_1.58 : 83
  Tetrandrine_12.5 : 84
  Tetrandrine_25.0 : 85
  Tetrandrine_3.17 : 86
  Tetrandrine_50.0 : 87
  Tetrandrine_6.25 : 88
id2label:
  0 : Berberine Chloride_0.04
  1 : Berberine Chloride_0.08
  2 : Berberine Chloride_0.17
  3 : Berberine Chloride_0.42
  4 : Berberine Chloride_0.75
  5 : Berberine Chloride_1.58
  6 : Berberine Chloride_12.5
  7 : Berberine Chloride_25.0
  8 : Berberine Chloride_3.17
  9 : Berberine Chloride_50.0
  10 : Berberine Chloride_6.25
  11 : Brefeldin A_0.04
  12 : Brefeldin A_0.08
  13 : Brefeldin A_0.17
  14 : Brefeldin A_0.42
  15 : Brefeldin A_0.75
  16 : Brefeldin A_1.58
  17 : Brefeldin A_12.5
  18 : Brefeldin A_25.0
  19 : Brefeldin A_3.17
  20 : Brefeldin A_50.0
  21 : Brefeldin A_6.25
  22 : DFSO_0.0
  23 : Fluphenazine_0.04
  24 : Fluphenazine_0.08
  25 : Fluphenazine_0.17
  26 : Fluphenazine_0.42
  27 : Fluphenazine_0.75
  28 : Fluphenazine_1.58
  29 : Fluphenazine_12.5
  30 : Fluphenazine_25.0
  31 : Fluphenazine_3.17
  32 : Fluphenazine_50.0
  33 : Fluphenazine_6.25
  34 : Latrunculin B_0.04
  35 : Latrunculin B_0.08
  36 : Latrunculin B_0.17
  37 : Latrunculin B_0.42
  38 : Latrunculin B_0.75
  39 : Latrunculin B_1.58
  40 : Latrunculin B_12.5
  41 : Latrunculin B_25.0
  42 : Latrunculin B_3.17
  43 : Latrunculin B_50.0
  44 : Latrunculin B_6.25
  45 : Nocodazole_0.04
  46 : Nocodazole_0.08
  47 : Nocodazole_0.17
  48 : Nocodazole_0.42
  49 : Nocodazole_0.75
  50 : Nocodazole_1.58
  51 : Nocodazole_12.5
  52 : Nocodazole_25.0
  53 : Nocodazole_3.17
  54 : Nocodazole_50.0
  55 : Nocodazole_6.25
  56 : Rapamycin_0.04
  57 : Rapamycin_0.08
  58 : Rapamycin_0.17
  59 : Rapamycin_0.42
  60 : Rapamycin_0.75
  61 : Rapamycin_1.58
  62 : Rapamycin_12.5
  63 : Rapamycin_25.0
  64 : Rapamycin_3.17
  65 : Rapamycin_50.0
  66 : Rapamycin_6.25
  67 : Rotenone_0.04
  68 : Rotenone_0.08
  69 : Rotenone_0.17
  70 : Rotenone_0.42
  71 : Rotenone_0.75
  72 : Rotenone_1.58
  73 : Rotenone_12.5
  74 : Rotenone_25.0
  75 : Rotenone_3.17
  76 : Rotenone_50.0
  77 : Rotenone_6.25
  78 : Tetrandrine_0.04
  79 : Tetrandrine_0.08
  80 : Tetrandrine_0.17
  81 : Tetrandrine_0.42
  82 : Tetrandrine_0.75
  83 : Tetrandrine_1.58
  84 : Tetrandrine_12.5
  85 : Tetrandrine_25.0
  86 : Tetrandrine_3.17
  87 : Tetrandrine_50.0
  88 : Tetrandrine_6.25
metadata_output_columns : ['folder_name', 'file_name1', 'file_name2',
                           'file_name3', 'file_name4','well_id', 'compound_name', 'concentration']
train_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    _target_: src.utils.to_list
    to_tensor:
      _target_: torchvision.transforms.ToTensor
    normalize:
      _target_: torchvision.transforms.Normalize
      mean: [163.24,  536.39, 425.26, 581.64]
      std: [ 204.27, 1386.95, 917.2 , 519.7 ]
    vertical_filp:
      _target_:  torchvision.transforms.RandomVerticalFlip
    horizontal_flip:
      _target_:  torchvision.transforms.RandomHorizontalFlip
test_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    _target_: src.utils.to_list
    to_tensor:
      _target_: torchvision.transforms.ToTensor
    normalize:
      _target_: torchvision.transforms.Normalize
      mean: [163.24,  536.39, 425.26, 581.64]
      std: [ 204.27, 1386.95, 917.2 , 519.7 ]